<?php
/**************
* File: Mapeditor.php
* Creates map files quickly and efficently
* for Pits of Doom
**************/
session_start();
include('mapsymbols.php'); //all our map symbols

//creating a new map file
if (isset($_POST['export'])) {

	//We create the file for the download
	header('Content-type: text');

	//It'll be called [mapname]_[level].txt
	header('Content-Disposition: attachment; filename="' . $_SESSION['name'] . '_' . $_SESSION['level'] . '.txt"');
	
	//now output the file information
	echo "/**************
* File: " . $_SESSION['name'] . "
* Level: " . $_SESSION['level'] . "\n
* Dimensions: " . $_SESSION['width'] . " x " . $_SESSION['height'] . "
* Created On: " . date('F j, Y h:i:s A', time()) . "\n
* Generated By: Pits of Doom Map Editor\n
**************/
";
	
	for ($i = 0; $i <= $_SESSION['height']; $i++) {
		for ($j = 0; $j <= $_SESSION['width']; $j++) {
			echo $_POST[$i . "_" . $j] . " ";
    }
				echo "
";
  }
}

if ($_POST['reset']) {
	unset($_SESSION);
}

//start creating our map, setup our map variables
if ($_POST['startmap']) { 

	if (!$_POST['width'] || $_POST['width'] <= 0) {
		$error = "This map must have a valid width.";
  } else {
		$_SESSION['width'] = $_POST['width'];
  }
		
	if (!$_POST['height'] || $_POST['height'] <= 0) {
		$error = "This map must have a valid height.";
  } else {
		$_SESSION['height'] = $_POST['height'];
  }
		
	if (!$_POST['name']) {
		$_SESSION['name'] = "";
  } else {
		$_SESSION['name'] = $_POST['name'];
  }
		
	if (!$_POST['level']) {
		$_SESSION['level'] = 1;
  } else {
		$_SESSION['level'] = $_POST['level'];
  }
} 

// not trying to export a file
if (!isset($_POST['export'])) {
?>
<html>
  <head>
    <title>Pits of Doom - Map Editor</title>
    <script language="javascript">
			// this changes the background color of the cell
      function setColor(object) {
        object.style.backgroundColor = object.options[object.selectedIndex].style.backgroundColor;
        object.style.color = object.options[object.selectedIndex].style.color;
      }

			// this resets the background color of the cell
      function resetColors(object) {
        var i;

        for (i = 0; i < (object.length-2); i++) {
          setColor(object[i]);
        }
      }
    </script>
  </head>
  <body
    <?php
    if (isset($_SESSION['width']) && isset($_SESSION['height'])) {
      echo "onLoad=\"resetColors(form)\"";
    }
    ?>>
    <form action="#" method="post" name="form">
      <?php
      //first they have to select the map information
      if (!isset($_SESSION['width']) && !isset($_SESSION['height'])) {
      ?>
      <p align="center">
        <strong>Map Settings</strong>
        <?php
          if (isset($error)) {
            echo '<p align="center">Error: $error</p>';
          }
        ?>
      </p>
      <p>
        Name: <input type="text" name="name" />
      </p>
      <p>
        Level: <input type="text" name="level" /
      </p>
      <p>
        Width: <input type="text" name="width" />
      </p>
      <p>
        Height: <input type="text" name="height" />
      </p>
      <p align="center">
        <input type="submit" name="startmap" value="Start Editor" />
      </p>
      <?php
      } else { //display the map editor
        echo '<p align="center">
          <strong>Creating Map For ' . $_SESSION['name'] . ' Level ' . $_SESSION['level'] . '</strong><br/>
          Dimensions: ' . $_SESSION['width'] . ' X ' . $_SESSION['height'] . '<p/>';

        echo '<p align="center">
            <table cellpadding="2" cellspacing="2">
            <tr>
              <td></td>';

        //does this look familiar?!?
        for ($i = 0; $i < $_SESSION['width']; $i++) {
          echo "<td>$i</td>";
        }

        echo "</tr>";

        for ($i = 0; $i < $_SESSION['height']; $i++) {

          echo "<tr><td>$i</td>";

          for ($j = 0; $j < $_SESSION['width']; $j++) {
            echo "<td><select name=\"" . $i . "_" . $j . "\" onChange=\"setColor(this);\"";

            /*if (($i == 0) //the top row
             || ($j == 0) //down the left side
             || ($i == $_SESSION['height']) //the bottom row
             || ($j == $_SESSION['width']) //down the right side
              )
              echo " style=\"background-color: #CCC; color: #FFF;\"";
            */

            echo ">";

            //show all the options in the drop down box
            for ($r = 0; $r < sizeof($mapsymbols); $r++) {
              echo "<option value=\"" . $mapsymbols[$r] . "\"";

              //we colors that makes them easier to see
              if ($mapsymbols[$r] == "W") {
                echo " style=\"background-color: #CCC; color: #FFF;\"";
              }

              if ($mapsymbols[$r] == "E") {
                echo " style=\"background-color: #FFF; color: #000;\"";
              }

              if ($mapsymbols[$r] == "X") {
                echo " style=\"background-color: #000; color: #FFF;\"";
              }

              if ($mapsymbols[$r] == "L") {
                echo " style=\"background-color: #FFFF00; color: #000;\"";
              }

              if ($mapsymbols[$r] == "S") {
                echo " style=\"background-color: #0000FF; color: #FFF;\"";
              }

              if ($mapsymbols[$r] == "T") {
                echo " style=\"background-color: #009900; color: #FFF;\"";
              }

              if ($_POST[$i . "_" . $j] == $mapsymbols[$r]) {
                echo " selected";
              } else if (!$_POST[$i . "_" . $j]) {
                  if (($i == 0 && $mapsymbols[$r] == "W") //the top row
                   || ($j == 0 && $mapsymbols[$r] == "W") //down the left side
                   || ($i == $_SESSION['height']-1 && $mapsymbols[$r] == "W") //the bottom row
                   || ($j == $_SESSION['width']-1 && $mapsymbols[$r] == "W") //down the right side
                     ) {
                    echo " selected";
                  } else if ((($i != 0 && $mapsymbols[$r] == "E") //not the top row
                      && ($j != 0 && $mapsymbols[$r] == "E")) //not the left side
                      && (($i !=  $_SESSION['height']-1 && $mapsymbols[$r] == "E") //not the bottom row
                      && ($j != $_SESSION['width']-1 && $mapsymbols[$r] == "E")) //not the right side
                  ) {
                    echo " selected";
                  }
              }

              echo ">" . $mapsymbols[$r] . "</option>";
							
            } // end dropdown loop

            echo "</select></td>";
						
          } //end width loop

          echo "</tr>";

        } //end height loop

        echo '</table>
        <p align="center">
          <input type="submit" name="export" value="Export Map File"/>
          <input type="submit" name="reset" value="Start A New Map" onClick="return confirm(\'Are you sure?\')" />
        </p>';
      } //end display map editor
      ?>
    </form>
  </body>
</html>
<?php
} //end exporting a file
?>